name: kmeansGA
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  
  - numpy        
  - pandas
  - matplotlib
  - scikit-learn
  - pip          
  - brotli       
  - blas=1.0=mkl
  - bzip2
  - ca-certificates
  - freetype
  - jpeg
  - lerc
  - libffi
  - libpng
  - libtiff
  - libwebp-base
  - libdeflate
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - openssl
  - pillow
  - six
  - sqlite
  - tk
  - wheel
  - zlib
  - zstd
  - pip:
      - build==1.2.1
      - cachecontrol==0.14.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - cleo==2.1.0
      - colorama==0.4.6
      - crashtest==0.4.1
      - cycler==0.12.1
      - distlib==0.3.8
      - dulwich==0.21.7
      - et-xmlfile==1.1.0
      - fastjsonschema==2.19.1
      - filelock==3.13.3
      - fonttools==4.50.0
      - idna==3.6
      - importlib-metadata==7.1.0
      - installer==0.7.0
      - joblib==1.4.0
      - keyring==24.3.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.3
      - more-itertools==10.2.0
      - msgpack==1.0.8
      - niapy==2.1.0
      - openpyxl==3.1.2
      - packaging==24.0
      - poetry==1.8.2
      - poetry-core==1.9.0
      - poetry-plugin-export==1.7.1
      - ptyprocess==0.7.0
      - pyparsing==3.1.2
      - pyproject-hooks==1.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pywin32-ctypes==0.2.2
      - rapidfuzz==3.7.0
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - shellingham==1.5.4
      - threadpoolctl==3.4.0
      - tomlkit==0.12.4
      - trove-classifiers==2024.3.25
      - tzdata==2024.1
      - urllib3==2.2.1
      - virtualenv==20.25.1
      - zipp==3.18.1

