name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.10'
          environment-file: environment.yml

      - name: Install dependencies
        run: |
          mamba install --yes --file environment.yml  # Install dependencies specified in the yml file

      - name: Lint with flake8
        run: |
          mamba run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          mamba run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests with pytest
        run: |
          mamba run pytest  # Run tests in the environment
