name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: '3.10'
          environment-file: environment.yml  

      - name: Install mamba
        run: |
          conda install mamba -n base -c conda-forge

      - name: Cache conda
        uses: actions/cache@v3
        with:
          path: ~/.conda
          key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Install dependencies
        run: |
          mamba env update --file environment.yml --name base

      - name: Lint with flake8
        run: |
          mamba run -n base flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          mamba run -n base flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          mamba run -n base pytest
